use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=data/");

    let data_dir = Path::new("data/answers");
    let input_file = data_dir.join("wordle-answers-alphabetical.txt");

    let content = fs::read_to_string(&input_file)
        .unwrap_or_else(|e| panic!("Failed to read {:?}: {}", input_file, e));

    let words: Vec<String> = content
        .lines()
        .filter(|line| !line.is_empty())
        .map(|line| line.trim().to_lowercase())
        .collect();

    for word in &words {
        if word.len() != 5 {
            panic!("Word '{}' is not 5 characters", word);
        }
        if !word.bytes().all(|b| b.is_ascii_lowercase()) {
            panic!("Word '{}' contains non-ASCII characters", word);
        }
    }

    let word_count = words.len();
    let concatenated: String = words.concat();

    let mut freq = [0u32; 26];
    for word in &words {
        let mut seen = [false; 26];
        for b in word.bytes() {
            let idx = (b - b'a') as usize;
            if !seen[idx] {
                seen[idx] = true;
                freq[idx] += 1;
            }
        }
    }

    let freq_str: Vec<String> = freq.iter().map(|f| format!("    {},", f)).collect();

    let output = format!(
        "// Auto-generated by build.rs - DO NOT EDIT\n\
         // Source: data/answers/wordle-answers-alphabetical.txt\n\n\
         pub const WORD_COUNT: usize = {};\n\n\
         pub const WORDS: &[u8] = b\"{}\";\n\n\
         pub const LETTER_FREQ: [u32; 26] = [\n{}\n];\n",
        word_count,
        concatenated,
        freq_str.join("\n")
    );

    let dest_path = Path::new("src/words.rs");
    fs::write(&dest_path, output).expect("Failed to write src/words.rs");
}
